#!/bin/bash
#SBATCH -N NUMNODESBLANK
#SBATCH -n NUMTASKSPERNODEBLANK
#SBATCH -c 4
#SBATCH -t 02:00:00          
#SBATCH -J MD
#SBATCH -o runout.%j  
#SBATCH -e runerr.%j  
#SBATCH -p PARTITIONBLANK
#SBATCH --gres=gpu:GPUBLANK:NUMTASKSPERNODEBLANK
##SBATCH --gpus-per-node=1
##SBATCH --constraint=a100
#SBATCH --mem=16000

infile=lammps.in
num_gpu_per_node=NUMTASKSPERNODEBLANK
nodes_per_run=NUMNODESBLANK
#Num nodes times num gpu
num_task=$((num_gpu_per_node*nodes_per_run))




source /ccs/home/[user-id]/.bashrc
module load cuda/12.4.1-fasrc01 cudnn/9.5.1.17_cuda12-fasrc01 gcc/12.2.0-fasrc01 intel-mkl/24.2.1-fasrc01 openmpi/4.1.5-fasrc01
export LD_PRELOAD=/n/sw/helmod-rocky8/apps/Core/gcc/12.2.0-fasrc01/lib64/libstdc++.so.6
micromamba activate [path/to/env]/env-torch-nequip-allegro-lmp/
nvidia-smi
export OMP_NUM_THREADS=1
mpirun -np $num_task [path/to/lammps]/lammps/build_GPUNAMEBLANK/lmp -k on g $num_gpu_per_node -sf kk -pk kokkos newton on neigh half -in $infile
